name: get_citation_data

on:
  page_build:
  schedule:
    - cron:  '0 6 * * 1'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Reqs
      run: |
        pip install -r google_scholar_crawler/requirements.txt
    - name: Run
      run: |
        cd ./google_scholar_crawler
        python main.py
    - name: Commit and Push
      run: |
        git add assets/results/
        git diff --cached --quiet && echo "No changes to commit" && exit 0
        git config user.email "zhounan2012@msn.com"
        git config user.name "morthlee"
        git commit -m "* update $(date '+%Y-%m-%d %H:%M:%S')"
        git push
